FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGltcG9ydC12bS1hcGIKZGVzY3JpcHRpb246IEltcG9ydCBWaXJ0\
dWFsIE1hY2hpbmUKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAp0YWdzOgogIC0gdmly\
dHVhbG1hY2hpbmUKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IEltcG9ydCBWaXJ0dWFsIE1hY2hp\
bmUKICBpbWFnZVVybDogaHR0cHM6Ly9jZG4ucGJyZC5jby9pbWFnZXMvSDVHdXRkNy5wbmcKcGxh\
bnM6CiAgLSBuYW1lOiB2bXdhcmUKICAgIGRlc2NyaXB0aW9uOiBJbXBvcnQgYSB2aXJ0dWFsIG1h\
Y2hpbmUgZnJvbSBWTXdhcmUgdkNlbnRlcgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6CiAg\
ICAgIGRpc3BsYXlOYW1lOiBJbXBvcnQgZnJvbSBWTXdhcmUKICAgIHBhcmFtZXRlcnM6CiAgICAg\
IC0gdGl0bGU6IE9wZW5TaGlmdCBBZG1pbiBVc2VybmFtZQogICAgICAgIG5hbWU6IGFkbWluX3Vz\
ZXIKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAtIHRp\
dGxlOiBPcGVuU2hpZnQgQWRtaW4gUGFzc3dvcmQKICAgICAgICBuYW1lOiBhZG1pbl9wYXNzd29y\
ZAogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgICAgZGlz\
cGxheV90eXBlOiBwYXNzd29yZAogICAgICAtIHRpdGxlOiBWTXdhcmUgVVJMIHRvIEVYU2kKICAg\
ICAgICBuYW1lOiB1cmwKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1\
ZQogICAgICAtIHRpdGxlOiBWaXJ0dWFsIE1hY2hpbmUgTmFtZQogICAgICAgIG5hbWU6IHZtX25h\
bWUKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAtIHRp\
dGxlOiBWTXdhcmUgQWRtaW4gVXNlcm5hbWUKICAgICAgICBuYW1lOiB1c2VybmFtZQogICAgICAg\
IHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgICAgZGlzcGxheV90eXBl\
OiB1c2VybmFtZQogICAgICAtIHRpdGxlOiBWTXdhcmUgQWRtaW4gUGFzc3dvcmQKICAgICAgICBu\
YW1lOiBwYXNzd29yZAogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVl\
CiAgICAgICAgZGlzcGxheV90eXBlOiBwYXNzd29yZAogICAgICAtIHRpdGxlOiBPcGVyYXRpbmcg\
c3lzdGVtIHR5cGUKICAgICAgICBuYW1lOiBvc190eXBlCiAgICAgICAgZGVmYXVsdDogbGludXgK\
ICAgICAgICBlbnVtOiBbJ2xpbnV4JywgJ3dpbmRvd3MnXQogICAgICAgIHR5cGU6IGVudW0KICAg\
ICAgLSB0aXRsZTogVmlydHVhbCBtYWNoaW5lIGlzIGltcG9ydGVkIGFzCiAgICAgICAgbmFtZTog\
aW1hZ2VfdHlwZQogICAgICAgIGRlZmF1bHQ6IG92bQogICAgICAgIGVudW06IFsnb3ZtJywgJ3Rl\
bXBsYXRlJ10KICAgICAgICB0eXBlOiBlbnVtICAgICAgICAKICAtIG5hbWU6IHVybAogICAgZGVz\
Y3JpcHRpb246IENyZWF0ZSBhIHZpcnR1YWwgbWFjaGluZSBmcm9tIGEgZG93bmxvYWRlZCBkaXNr\
IGltYWdlCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToKICAgICAgZGlzcGxheU5hbWU6IElt\
cG9ydCBmcm9tIFVSTAogICAgcGFyYW1ldGVyczoKICAgICAgLSB0aXRsZTogT3BlblNoaWZ0IEFk\
bWluIFVzZXIKICAgICAgICBuYW1lOiBhZG1pbl91c2VyCiAgICAgICAgdHlwZTogc3RyaW5nCiAg\
ICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgLSB0aXRsZTogT3BlblNoaWZ0IEFkbWluIFBhc3N3\
b3JkCiAgICAgICAgbmFtZTogYWRtaW5fcGFzc3dvcmQKICAgICAgICB0eXBlOiBzdHJpbmcKICAg\
ICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAgIGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAg\
LSB0aXRsZTogRGlzayBJbWFnZSBVUkwKICAgICAgICBuYW1lOiBkaXNrX2ltYWdlX3VybAogICAg\
ICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgIC0gdGl0bGU6IFZp\
cnR1YWwgTWFjaGluZSBUeXBlCiAgICAgICAgbmFtZTogdm1fdHlwZQogICAgICAgIHR5cGU6IGVu\
dW0KICAgICAgICBlbnVtOiBbJ2RlZmF1bHQnXQogICAgICAgIHJlcXVpcmVkOiBUcnVlCiAgICAg\
ICAgZGVmYXVsdDogZGVmYXVsdAogICAgICAgIGRpc3BsYXlfdHlwZTogc2VsZWN0CiAgICAgIC0g\
dGl0bGU6IFZpcnR1YWwgTWFjaGluZSBOYW1lCiAgICAgICAgbmFtZTogdm1fbmFtZQogICAgICAg\
IHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgIC0gdGl0bGU6IE51bWJl\
ciBvZiBDUFVzCiAgICAgICAgbmFtZTogbnJfY3B1cwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAg\
ICAgICAgdHlwZTogaW50CiAgICAgICAgZGVmYXVsdDogMQogICAgICAtIHRpdGxlOiBNZW1vcnkg\
KGluIE1lZ2FieXRlcykKICAgICAgICBuYW1lOiBtZW0KICAgICAgICByZXF1aXJlZDogdHJ1ZQog\
ICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDEwMjQK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
RUN yum -y install libvirt-client curl qemu-img wget && yum clean all
# We need this to get oc v3.9 due to the issue with oc apply. Once we would update apb-base to use 3.9 we can remove it
RUN wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN tar zxvf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN mv openshift-origin-client-tools-v3.9.0-191fece-linux-64bit/oc /usr/bin
RUN rm -rf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
RUN chmod u+x /usr/bin/oc
# future removal ends here
COPY bin/run-v2v.sh /v2v.d/
RUN setfacl -Rm u:apb:rwx /v2v.d
USER apb
