FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGltcG9ydC12bS1hcGIKZGVzY3JpcHRpb246IEltcG9ydCBWaXJ0\
dWFsIE1hY2hpbmUKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAp0YWdzOgogIC0gdmly\
dHVhbG1hY2hpbmUKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IEltcG9ydCBWaXJ0dWFsIE1hY2hp\
bmUKICBpbWFnZVVybDogaHR0cHM6Ly9jZG4ucGJyZC5jby9pbWFnZXMvSDVHdXRkNy5wbmcKICBs\
b25nRGVzY3JpcHRpb246IHwKICAgICBJbXBvcnQgVmlydHVhbCBNYWNoaW5lIGZyb20gYW4gZXhp\
c3RpbmcgaW1hZ2Ugb3IgYSBWTXdhcmUgZW52aXJvbm1lbnQuCnBsYW5zOgogIC0gbmFtZTogdXJs\
CiAgICBkZXNjcmlwdGlvbjogQ3JlYXRlIGEgdmlydHVhbCBtYWNoaW5lIGZyb20gYSBkb3dubG9h\
ZGVkIGRpc2sgaW1hZ2UuCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToKICAgICAgZGlzcGxh\
eU5hbWU6IGEuIEltcG9ydCBmcm9tIFVSTC4KICAgIHBhcmFtZXRlcnM6CiAgICAgIC0gdGl0bGU6\
IERpc2sgSW1hZ2UgVVJMCiAgICAgICAgbmFtZTogZGlza19pbWFnZV91cmwKICAgICAgICB0eXBl\
OiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAtIHRpdGxlOiBPcGVyYXRpbmcg\
c3lzdGVtIHR5cGUKICAgICAgICBuYW1lOiBvc190eXBlCiAgICAgICAgZGVmYXVsdDogbGludXgK\
ICAgICAgICBlbnVtOiBbJ2xpbnV4JywgJ3dpbmRvd3MnXQogICAgICAgIHR5cGU6IGVudW0KICAg\
ICAgLSB0aXRsZTogVmlydHVhbCBNYWNoaW5lIE5hbWUKICAgICAgICBuYW1lOiB2bV9uYW1lCiAg\
ICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgLSB0aXRsZTog\
TnVtYmVyIG9mIENvcmVzCiAgICAgICAgbmFtZTogbnJfY29yZXMKICAgICAgICByZXF1aXJlZDog\
dHJ1ZQogICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDEKICAgICAgLSB0aXRsZTog\
TWVtb3J5IChNaUIpCiAgICAgICAgbmFtZTogbWVtCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAg\
ICAgICB0eXBlOiBpbnQKICAgICAgICBkZWZhdWx0OiAxMDI0CiAgICAgIC0gdGl0bGU6IERpc2sg\
U2l6ZSAoR2lCKSAobGVhdmUgYXQgMCB0byBhdXRvIGRldGVjdCBzaXplKQogICAgICAgIG5hbWU6\
IGRpc2tfc2l6ZV9nYgogICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDAKICAgICAg\
LSB0aXRsZTogU3RvcmFnZSBDbGFzcyAobGVhdmUgZW1wdHkgdG8gdXNlIHRoZSBkZWZhdWx0IHN0\
b3JhZ2UgY2xhc3MpCiAgICAgICAgbmFtZTogc3RvcmFnZV9jbGFzcwogICAgICAgIHR5cGU6IHN0\
cmluZwogIC0gbmFtZTogdXJsLXRlbXBsYXRlCiAgICBkZXNjcmlwdGlvbjogQ3JlYXRlIGEgdmly\
dHVhbCBtYWNoaW5lIHRlbXBsYXRlIGZyb20gYSBkb3dubG9hZGVkIGRpc2sgaW1hZ2UuCiAgICBm\
cmVlOiBUcnVlCiAgICBtZXRhZGF0YToKICAgICAgZGlzcGxheU5hbWU6IGIuIEltcG9ydCBhcyBh\
IHRlbXBsYXRlIGZyb20gVVJMLgogICAgcGFyYW1ldGVyczoKICAgICAgLSB0aXRsZTogT3BlblNo\
aWZ0IEFkbWluIFVzZXJuYW1lCiAgICAgICAgbmFtZTogYWRtaW5fdXNlcgogICAgICAgIHR5cGU6\
IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgIC0gdGl0bGU6IE9wZW5TaGlmdCBB\
ZG1pbiBQYXNzd29yZAogICAgICAgIG5hbWU6IGFkbWluX3Bhc3N3b3JkCiAgICAgICAgdHlwZTog\
c3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgICBkaXNwbGF5X3R5cGU6IHBhc3N3\
b3JkCiAgICAgIC0gdGl0bGU6IERpc2sgSW1hZ2UgVVJMCiAgICAgICAgbmFtZTogZGlza19pbWFn\
ZV91cmwKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAt\
IHRpdGxlOiBPcGVyYXRpbmcgc3lzdGVtIHR5cGUKICAgICAgICBuYW1lOiBvc190eXBlCiAgICAg\
ICAgZGVmYXVsdDogbGludXgKICAgICAgICBlbnVtOiBbJ2xpbnV4JywgJ3dpbmRvd3MnXQogICAg\
ICAgIHR5cGU6IGVudW0KICAgICAgLSB0aXRsZTogVGVtcGxhdGUgTmFtZQogICAgICAgIG5hbWU6\
IHZtX25hbWUKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAg\
ICAtIHRpdGxlOiBOdW1iZXIgb2YgQ29yZXMKICAgICAgICBuYW1lOiBucl9jb3JlcwogICAgICAg\
IHJlcXVpcmVkOiB0cnVlCiAgICAgICAgdHlwZTogaW50CiAgICAgICAgZGVmYXVsdDogMQogICAg\
ICAtIHRpdGxlOiBNZW1vcnkgKE1pQikKICAgICAgICBuYW1lOiBtZW0KICAgICAgICByZXF1aXJl\
ZDogdHJ1ZQogICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDEwMjQKICAgICAgLSB0\
aXRsZTogRGlzayBTaXplIChHaUIpIChsZWF2ZSBhdCAwIHRvIGF1dG8gZGV0ZWN0IHNpemUpCiAg\
ICAgICAgbmFtZTogZGlza19zaXplX2diCiAgICAgICAgdHlwZTogaW50CiAgICAgICAgZGVmYXVs\
dDogMAogICAgICAtIHRpdGxlOiBTdG9yYWdlIENsYXNzIChsZWF2ZSBlbXB0eSB0byB1c2UgdGhl\
IGRlZmF1bHQgc3RvcmFnZSBjbGFzcykKICAgICAgICBuYW1lOiBzdG9yYWdlX2NsYXNzCiAgICAg\
ICAgdHlwZTogc3RyaW5nCg=="



RUN chmod -R g=u /opt/{ansible,apb}
RUN yum -y install libvirt-client curl qemu-img wget && yum clean all
# We need this to get oc v3.9 due to the issue with oc apply. Once we would update apb-base to use 3.9 we can remove it
RUN wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN tar zxvf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN mv openshift-origin-client-tools-v3.9.0-191fece-linux-64bit/oc /usr/bin
RUN rm -rf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
RUN chmod u+x /usr/bin/oc
# future removal ends here
COPY bin/run-v2v.sh /v2v.d/
RUN setfacl -Rm u:apb:rwx /v2v.d

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY templates /opt/ansible/templates

USER apb
