FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGltcG9ydC12bS1hcGIKZGVzY3JpcHRpb246IEltcG9ydCBWaXJ0\
dWFsIE1hY2hpbmUKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAp0YWdzOgogIC0gdmly\
dHVhbG1hY2hpbmUKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IEltcG9ydCBWaXJ0dWFsIE1hY2hp\
bmUKICBpbWFnZVVybDogaHR0cHM6Ly9jZG4ucGJyZC5jby9pbWFnZXMvSDVHdXRkNy5wbmcKICBs\
b25nRGVzY3JpcHRpb246IHwKICAgICBJbXBvcnQgVmlydHVhbCBNYWNoaW5lIGZyb20gYW4gZXhp\
c3RpbmcgaW1hZ2Ugb3IgYSBWTXdhcmUgZW52aXJvbm1lbnQuCnBsYW5zOgogIC0gbmFtZTogdm13\
YXJlCiAgICBkZXNjcmlwdGlvbjogSW1wb3J0IGEgdmlydHVhbCBtYWNoaW5lIGZyb20gVk13YXJl\
IHZDZW50ZXIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOgogICAgICBkaXNwbGF5TmFtZTog\
SW1wb3J0IGZyb20gVk13YXJlCiAgICBwYXJhbWV0ZXJzOgogICAgICAtIHRpdGxlOiBPcGVuU2hp\
ZnQgQWRtaW4gVXNlcm5hbWUKICAgICAgICBuYW1lOiBhZG1pbl91c2VyCiAgICAgICAgdHlwZTog\
c3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgLSB0aXRsZTogT3BlblNoaWZ0IEFk\
bWluIFBhc3N3b3JkCiAgICAgICAgbmFtZTogYWRtaW5fcGFzc3dvcmQKICAgICAgICB0eXBlOiBz\
dHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAgIGRpc3BsYXlfdHlwZTogcGFzc3dv\
cmQKICAgICAgLSB0aXRsZTogVk13YXJlIFVSTCB0byBFWFNpCiAgICAgICAgbmFtZTogdXJsCiAg\
ICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgLSB0aXRsZTog\
VmlydHVhbCBNYWNoaW5lIE5hbWUKICAgICAgICBuYW1lOiB2bV9uYW1lCiAgICAgICAgdHlwZTog\
c3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgLSB0aXRsZTogVk13YXJlIEFkbWlu\
IFVzZXJuYW1lCiAgICAgICAgbmFtZTogdXNlcm5hbWUKICAgICAgICB0eXBlOiBzdHJpbmcKICAg\
ICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAgIGRpc3BsYXlfdHlwZTogdXNlcm5hbWUKICAgICAg\
LSB0aXRsZTogVk13YXJlIEFkbWluIFBhc3N3b3JkCiAgICAgICAgbmFtZTogcGFzc3dvcmQKICAg\
ICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAgIGRpc3BsYXlf\
dHlwZTogcGFzc3dvcmQKICAgICAgLSB0aXRsZTogT3BlcmF0aW5nIFN5c3RlbSBUeXBlCiAgICAg\
ICAgbmFtZTogb3NfdHlwZQogICAgICAgIGRlZmF1bHQ6IGxpbnV4CiAgICAgICAgZW51bTogWyds\
aW51eCcsICd3aW5kb3dzJ10KICAgICAgICB0eXBlOiBlbnVtCiAgICAgIC0gdGl0bGU6IEltcG9y\
dCBWaXJ0dWFsIE1hY2hpbmUgYXMKICAgICAgICBuYW1lOiBpbWFnZV90eXBlCiAgICAgICAgZGVm\
YXVsdDogdm0KICAgICAgICBlbnVtOiBbJ3ZtJywgJ3RlbXBsYXRlJ10KICAgICAgICB0eXBlOiBl\
bnVtICAgICAgICAKICAtIG5hbWU6IHVybAogICAgZGVzY3JpcHRpb246IENyZWF0ZSBhIHZpcnR1\
YWwgbWFjaGluZSBmcm9tIGEgZG93bmxvYWRlZCBkaXNrIGltYWdlCiAgICBmcmVlOiBUcnVlCiAg\
ICBtZXRhZGF0YToKICAgICAgZGlzcGxheU5hbWU6IEltcG9ydCBmcm9tIFVSTAogICAgcGFyYW1l\
dGVyczoKICAgICAgLSB0aXRsZTogRGlzayBJbWFnZSBVUkwKICAgICAgICBuYW1lOiBkaXNrX2lt\
YWdlX3VybAogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAg\
IC0gdGl0bGU6IE9wZXJhdGluZyBzeXN0ZW0gdHlwZQogICAgICAgIG5hbWU6IG9zX3R5cGUKICAg\
ICAgICBkZWZhdWx0OiBsaW51eAogICAgICAgIGVudW06IFsnbGludXgnLCAnd2luZG93cyddCiAg\
ICAgICAgdHlwZTogZW51bQogICAgICAtIHRpdGxlOiBWaXJ0dWFsIE1hY2hpbmUgTmFtZQogICAg\
ICAgIG5hbWU6IHZtX25hbWUKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDog\
dHJ1ZQogICAgICAtIHRpdGxlOiBOdW1iZXIgb2YgQ29yZXMKICAgICAgICBuYW1lOiBucl9jb3Jl\
cwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgICAgdHlwZTogaW50CiAgICAgICAgZGVmYXVs\
dDogMQogICAgICAtIHRpdGxlOiBNZW1vcnkgKE1pQikKICAgICAgICBuYW1lOiBtZW0KICAgICAg\
ICByZXF1aXJlZDogdHJ1ZQogICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDEwMjQK\
ICAgICAgLSB0aXRsZTogRGlzayBTaXplIChHaUIpCiAgICAgICAgbmFtZTogZGlza19zaXplX2di\
CiAgICAgICAgdHlwZTogaW50CiAgICAgICAgZGVmYXVsdDogMAogICAgICAtIHRpdGxlOiBTdG9y\
YWdlIENsYXNzCiAgICAgICAgbmFtZTogc3RvcmFnZV9jbGFzcwogICAgICAgIHR5cGU6IHN0cmlu\
ZwogICAgICAtIHRpdGxlOiBWaXJ0dWFsIG1hY2hpbmUgaXMgaW1wb3J0ZWQgYXMKICAgICAgICBu\
YW1lOiBpbWFnZV90eXBlCiAgICAgICAgZGVmYXVsdDogdm0KICAgICAgICBlbnVtOiBbJ3ZtJywg\
J3RlbXBsYXRlJ10KICAgICAgICB0eXBlOiBlbnVtCg=="

RUN chmod -R g=u /opt/{ansible,apb}
RUN yum -y install libvirt-client curl qemu-img wget && yum clean all
# We need this to get oc v3.9 due to the issue with oc apply. Once we would update apb-base to use 3.9 we can remove it
RUN wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN tar zxvf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
RUN mv openshift-origin-client-tools-v3.9.0-191fece-linux-64bit/oc /usr/bin
RUN rm -rf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
RUN chmod u+x /usr/bin/oc
# future removal ends here
COPY bin/run-v2v.sh /v2v.d/
RUN setfacl -Rm u:apb:rwx /v2v.d

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY templates /opt/ansible/templates

USER apb
